import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { MainLayout } from "@/app/componentes/MainLayout";

const inter = localFont({
    src: "../fonts/Inter-Medium.ttf",
    variable: "--font-inter",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return <MainLayout>{children}</MainLayout>;
}
